name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Git identity
      run: |
        git config --global user.email "frejamadsen1408@gmail.com"
        git config --global user.name "frmad"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Disable ESLint warnings
      run: echo "CI=false" >> .env

    - name: Build the app
      run: npm run build
    
    - name: Deploy the app to GitHub Pages
      run: npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Reference the secret here
        REACT_APP_EMAILJS_SERVICE: ${{ secrets.REACT_APP_EMAILJS_SERVICE }}
        REACT_APP_EMAILJS_TEMPLATE: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE }}
        REACT_APP_EMAILJS_KEY: ${{ secrets.REACT_APP_EMAILJS_KEY }}
